version: 0.2

phases:

  install:
    commands:
      - curl https://github.com/purescript/psc-package/releases/download/v0.2.3/linux64.tar.gz -L | tar xz
      - PATH="$PATH:$(pwd)/psc-package"

  pre_build:
    commands:
      - chmod +x *.sh
      - npm run prep

  build:
    commands:
      - npm run build

  post-build:
    commands:
      - ./publish.sh

artifacts:

  files:
    - build/**
