version: 0.1

phases:
  pre_build:
    commands:
      - echo "pre build"
      - chmod +x *.sh
      - curl https://github.com/purescript/psc-package/releases/download/v0.1.2/macos.tar.gz -L | tar xz

  build:
    commands:
      - echo "build"
      - PATH="$PATH:$(pwd)/psc-package" npm run prep
      - PATH="$PATH:$(pwd)/psc-package" npm run build
      - echo "publish"
      - ./publish.sh
